//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.CrossCutting.Localization.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your app description page..
        /// </summary>
        public static string ABOUTVIEW {
            get {
                return ResourceManager.GetString("ABOUTVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NuGet packages and jump-start your coding.
        /// </summary>
        public static string ADDNUGET {
            get {
                return ResourceManager.GetString("ADDNUGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aside Title.
        /// </summary>
        public static string ASIDETITLE {
            get {
                return ResourceManager.GetString("ASIDETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string CONTACTVIEW {
            get {
                return ResourceManager.GetString("CONTACTVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Web Hosting.
        /// </summary>
        public static string FINDWEBHOSTING {
            get {
                return ResourceManager.GetString("FINDWEBHOSTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GETTINGSTARTED {
            get {
                return ResourceManager.GetString("GETTINGSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this template to jump-start your ASP.NET MVC application..
        /// </summary>
        public static string HOMEMESSAGE {
            get {
                return ResourceManager.GetString("HOMEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string IFYOUDONTHAVEANACCOUNT {
            get {
                return ResourceManager.GetString("IFYOUDONTHAVEANACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string LANGCHINESE {
            get {
                return ResourceManager.GetString("LANGCHINESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANGENGLISH {
            get {
                return ResourceManager.GetString("LANGENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string LANGSPANISH {
            get {
                return ResourceManager.GetString("LANGSPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more….
        /// </summary>
        public static string LEARNMORE {
            get {
                return ResourceManager.GetString("LEARNMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LOGOFF {
            get {
                return ResourceManager.GetString("LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data you are entering exceeds the size of the field.
        /// </summary>
        public static string MAXLENGTH {
            get {
                return ResourceManager.GetString("MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string REMEMBERME {
            get {
                return ResourceManager.GetString("REMEMBERME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in English.
        /// </summary>
        public static string TESTTITLE {
            get {
                return ResourceManager.GetString("TESTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To learn more about ASP.NET MVC visit.
        /// </summary>
        public static string TOLEARNMORE {
            get {
                return ResourceManager.GetString("TOLEARNMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string USELOCALACCOUNT {
            get {
                return ResourceManager.GetString("USELOCALACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string USETHISAREA {
            get {
                return ResourceManager.GetString("USETHISAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest the following:.
        /// </summary>
        public static string WESUGGEST {
            get {
                return ResourceManager.GetString("WESUGGEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your logo here.
        /// </summary>
        public static string YOURLOGOHERE {
            get {
                return ResourceManager.GetString("YOURLOGOHERE", resourceCulture);
            }
        }
    }
}
